### ISSUE TITLE
GCP WORKLOAD IDENTITY SUPPORT - UNABLE TO CREATE NEW BATCH SNOWFLAKE DESTINATION

### ISSUE THREAD

**Issue by viggin543** [jitsucom/jitsu#875]
## Environment

- **Deploy method**:  K8S GCP SPOT INSTANCES
- **Jitsu version**:   `1.41.1`
- **OS**:  GCP container optimized OS
- **Cloud Provider**: GCP

## Description
when creating a new batch destination to snowflake, with a GCP bucket
![image](https://user-images.githubusercontent.com/6231756/160184564-cfa05466-7b27-4fec-964e-e78a5f568e0b.png)
like this.
The connection test fails and the connection is marked as failed.

However, it actually works and if you change the status of the destination in redis everything works fine.

existing destinations that were configured using workload identity work as well.
So it's probably only an issue with the connection test.

## Steps to reproduce

create a snowflake batch destination  using a GCP bucket and instead of the SERVICE ACCOUNT JSON
enter: `workload_identity`  ( as in the image above )

the connection test fails

## Expected behavior

the connection test should pass

## Actual behavior

the connection test fails

----

it is possible to work around this simply by editing the destination configuration in redis, ( changing the status flag to true )

**Comment by absorbb** [comment]
Hi @viggin543 
Thank you for reporting that. Fix will be released shortly

**Comment by absorbb** [comment]
Fixed in  [v1.41.2](https://github.com/jitsucom/jitsu/releases/tag/v1.41.2)

**Comment by viggin543** [comment]
@absorbb  still getting an error 

```Post "https://ka00000.us-central1.gcp.us-central1.gcp.us-central1.gcp.snowflakecomputing.com.snowflakecomputing.com:443/session/v1/login-request?databaseName=XXXX&requestId=872f9e31-c0b8-4c8f-92a6-f4b476225ad8&request_guid=9169831e-4b53-4d20-b1fe-6fef824a9df4&schemaName=XXXX&warehouse=XXXX": x509: certificate is valid for *.us-west-2.snowflakecomputing.com, *.us-west-2.aws.snowflakecomputing.com, *.global.snowflakecomputing.com, *.snowflakecomputing.com, *.prod1.us-west-2.aws.snowflakecomputing.com, *.prod2.us-west-2.aws.snowflakecomputing.com, not ka29700.us-central1.gcp.us-central1.gcp.us-central1.gcp.snowflakecomputing.com.snowflakecomputing.com (#400)```

it seems there's a typo in the domain

the configuration domain is:
`ka00000.us-central1.gcp.snowflakecomputing.com`

and the post request is to:

`ka00000.us-central1.gcp.us-central1.gcp.us-central1.gcp.snowflakecomputing.com.snowflakecomputing.com`

**Comment by absorbb** [comment]
@viggin543 
Please try to provide:
`ka00000.us-central1.gcp` 
to Account field instead of full configuration domain.

**Comment by viggin543** [comment]
@absorbb works thanks🙏
in the past, it was the full domain for sure!

**Comment by absorbb** [comment]
Will take a deeper look. Probably we need to update snowflake driver.
